name: ts-proto codegen

on:
  push:
    branches: [ main ]

permissions:
  contents: read

env:
  # Set the exact protoc version you want
  PROTOC_VERSION: "32.0"

jobs:
  codegen:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest ]

    steps:
      - name: Checkout
        # actions/checkout v5.0.0
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - name: Compute protoc archive name
        id: protoc-arch
        shell: bash
        run: |
          set -eu
          V="${PROTOC_VERSION}"
          OS="${{ runner.os }}"
          ARCH="${{ runner.arch }}"

          case "$OS" in
            Linux)  OS_ID="linux" ;;
            macOS)  OS_ID="osx" ;;
            *) echo "Unsupported OS: $OS" >&2; exit 1 ;;
          esac

          case "$ARCH" in
            X64)     CPU_ID="x86_64" ;;
            ARM64)   CPU_ID="aarch_64" ;;
            *) echo "Unsupported arch: $ARCH" >&2; exit 1 ;;
          esac

          FILE="protoc-${V}-${OS_ID}-${CPU_ID}.zip"
          TAG="v${V}"

          echo "file=$FILE" >> "$GITHUB_OUTPUT"
          echo "tag=$TAG"   >> "$GITHUB_OUTPUT"

      - name: Restore protoc cache
        id: protoc-cache
        # actions/cache v4.2.4
        uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809
        with:
          path: ~/.protoc
          key: protoc-${{ steps.protoc-arch.outputs.tag }}-${{ steps.protoc-arch.outputs.file }}-${{ runner.os }}

      - name: Install protoc ${{ env.PROTOC_VERSION }}
        if: steps.protoc-cache.outputs.cache-hit != 'true'
        shell: bash
        run: |
          set -eux
          mkdir -p "$HOME/.protoc"
          FILE="${{ steps.protoc-arch.outputs.file }}"
          TAG="${{ steps.protoc-arch.outputs.tag }}"
          URL="https://github.com/protocolbuffers/protobuf/releases/download/${TAG}/${FILE}"
          echo "Downloading $URL"
          curl -sSfL -o "$FILE" "$URL"
          unzip -o "$FILE" -d "$HOME/.protoc"
          rm -f "$FILE"
          # Persist for later steps
          echo "$HOME/.protoc/bin" >> "$GITHUB_PATH"
          echo "PROTOC_INCLUDE=$HOME/.protoc/include" >> "$GITHUB_ENV"

      - name: Add protoc to PATH and env (cache hit)
        if: steps.protoc-cache.outputs.cache-hit == 'true'
        shell: bash
        run: |
          echo "$HOME/.protoc/bin" >> "$GITHUB_PATH"
          echo "PROTOC_INCLUDE=$HOME/.protoc/include" >> "$GITHUB_ENV"

      - name: Verify protoc
        shell: bash
        run: |
          set -eux
          protoc --version
          test -d "$PROTOC_INCLUDE"

      - name: Set up Node
        # actions/setup-node v4.4.0
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: "24"

      - name: Enable corepack and pin pnpm 10.15.1
        shell: bash
        run: |
          set -eux
          corepack enable
          corepack prepare pnpm@10.15.1 --activate
          pnpm --version

      - name: Restore pnpm store cache
        id: pnpm-cache
        # actions/cache v4.2.4
        uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809
        with:
          path: ~/.pnpm-store
          key: pnpm-store-${{ runner.os }}-${{ hashFiles('build/typescript-deps/pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-store-${{ runner.os }}-

      - name: Prepare deps workspace
        shell: bash
        run: |
          set -eux
          mkdir -p build/typescript-deps
          if [ ! -f build/typescript-deps/package.json ]; then
            pnpm --dir build/typescript-deps init -y
            pnpm --dir build/typescript-deps pkg set name=ts-proto-deps
            pnpm --dir build/typescript-deps pkg set private=true
          fi

      - name: Install ts-proto 2.7.7 with pnpm
        shell: bash
        run: |
          set -eux
          pnpm --dir build/typescript-deps add ts-proto@2.7.7
          ./build/typescript-deps/node_modules/.bin/protoc-gen-ts_proto --version || true

      - name: Generate TypeScript from protobufs
        shell: bash
        run: |
          set -eux
          # Clean old outputs
          find ./build/typescript/gen -name '*.pb.ts' -delete || true
          # Generate for each .proto under src
          find src -type f -name '*.proto' -print0 | xargs -0 -n1 -I{} \
          protoc \
            --plugin=./build/typescript-deps/node_modules/.bin/protoc-gen-ts_proto \
            -I src \
            -I "$PROTOC_INCLUDE" \
            --ts_proto_out=./build/typescript/gen \
            --ts_proto_opt=esModuleInterop=true \
            --ts_proto_opt=env=browser \
            --ts_proto_opt=removeEnumPrefix=true \
            --ts_proto_opt=fileSuffix=.pb \
            --ts_proto_opt=outputJsonMethods=false \
            {}

      - name: Verify output
        shell: bash
        run: |
          set -eux
          ls -la build/typescript/gen
